package table

const PPP = "ppp"
const RP = "rp"
const SPK = "spk"
const ENTITY = "entity"
const PERKIRAAN_BIAYA = "perkiraan_biaya"
const PENGADAAN = "pengadaan"
const BDMU_PPP = "bdmu_ppp"
const BDMU_RP = "bdmu_rp"
const BDMUP_PPP = "bdmup_ppp"
const BDMUP_RP = "bdmup_rp"
const KELA_PPP = "kela_ppp"
const KELA_RP = "kela_rp"
const KELB_PPP = "kelb_ppp"
const KELB_RP = "kelb_rp"
const ULP_PERKIRAAN_BIAYA = "ulp_perkiraan_biaya"
const PPE_PERKIRAAN_BIAYA = "ppe_perkiraan_biaya"
const PPK_PENGADAAN = "ppk_pengadaan"
const PPK_RP = "ppk_rp"
const PPK_SPK = "ppk_spk"
const PPP_MESSAGE = "ppp_message"
const RP_MESSAGE = "rp_message"
const EMAIL_SESSION = "email_session"
